export const LOAD_UNIVERSITIES = 'LOAD_UNIVERSITIES';
export const LOAD_STATELIST = 'LOAD_STATELIST';
export const LOAD_CITYLIST = 'LOAD_CITYLIST';
export const LOAD_MODALITYLIST = 'LOAD_MODALITYLIST';
export const LOAD_CATEGORYLIST = 'LOAD_CATEGORYLIST';
export const LOAD_COURSESLIST = 'LOAD_COURSESLIST';
