export const LOAD_UNIVERSITIES = 'LOAD_UNIVERSITIES';
export const LOAD_STATELIST = 'LOAD_STATELIST';
export const LOAD_CITYLIST = 'LOAD_CITYLIST';
export const LOAD_MODALITYLIST = 'LOAD_MODALITYLIST';
export const LOAD_CATEGORYLIST = 'LOAD_CATEGORYLIST';
export const LOAD_COURSESLIST = 'LOAD_COURSESLIST';
export const UPDATE_BYSTATE = 'UPDATE_BYSTATE';
export const UPDATE_BYCITY = 'UPDATE_BYCITY';
export const UPDATE_BYCATEGORY = 'UPDATE_BYCATEGORY';

